### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getId()

### ISSUE THREAD

**Issue by iacopop** [SnowdogApps/magento2-theme-blank-sass#176]
In magento 2.2.1

after apply theme in backend i have this error in frontend:

```
[Mon Nov 27 09:25:49.306572 2017]
[:error] [pid 6185] [client ::1:52746] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php:802
Stack trace:
#0 /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php(713): Magento\\Framework\\View\\Model\\Layout\\Merge->_getPhysicalTheme(Object(Magento\\Theme\\Model\\Theme))
#1 /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php(662): Magento\\Framework\\View\\Model\\Layout\\Merge->_loadFileLayoutUpdatesXml()
#2 /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php(535): Magento\\Framework\\View\\Model\\Layout\\Merge->getFileLayoutUpdatesXml()
#3 /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php(514): Magento\\Framework\\View\\Model\\Layout\\Merge->_fetchPackageLayoutUpdates('default')
#4 /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php(438): Magento\\Framework\\View\\Model\\Layout\\Merge->_merge('default')
#5 /var/www/magento221/vendor/magento/framework/View/Layout/Builder.php(86): Magento\\ in /var/www/magento221/vendor/magento/framework/View/Model/Layout/Merge.php on line 802
```

**Comment by Igloczek** [comment]
Sorry, but we didn't edit templates or layouts in this theme, all code is inherited from the LESS based "Blank" theme.
